server:
  port: 8080

spring:
  webflux:
    multipart:
      max-in-memory-size: 4MB
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/proxycache}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/proxydb}
    username: ${SPRING_DATASOURCE_USERNAME:proxyuser}
    password: ${SPRING_DATASOURCE_PASSWORD:proxypass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG